### ISSUE TITLE
Downloader is not using bestaudio

### ISSUE THREAD

**Issue by ddelange** [dskleingeld/HomeAutomation#28]
[downloader](https://github.com/dskleingeld/HomeAutomation/blob/b7d98a90a0b709443334f8125524cc5eda703d5a/src/input/youtube_downloader.rs#L46) should use `bestaudio[acodec=opus]/bestaudio/best` (`webm` file as result) in order to obtain 40kHz sound (use e.g. [spek](spek.cc) for debugging). Of course, you can convert the result to `m4a` if that's your preferred format.

example with postprocessing: https://github.com/ddelange/yt/blob/master/yt.sh#L263

**Comment by dskleingeld** [comment]
forgot to respond but was implemented in 371dfc9d040883e36b6e366e204c0f5c15788add, thanks for closing
